//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADEnt.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TablesModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TablesModel()
        {
            this.newEquipment = new HashSet<newEquipment>();
        }
    
        public int intModelID { get; set; }
        public string strName { get; set; }
        public Nullable<int> intManufacturerID { get; set; }
        public Nullable<int> intSMCSFamilyID { get; set; }
        public string strImage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<newEquipment> newEquipment { get; set; }
        public virtual TablesManufacturer TablesManufacturer { get; set; }
    }
}
